version = 0.1

extensions = ['chomp@0.1:npm']

[[task]]
name = 'build'
deps = ['src/extension.mjs', 'importmap.json', 'rollup-config.mjs']
target = 'dist/extension.js'
run = 'jspm build -r @babel/helper-module-transforms=@babel/helper-module-transforms@7.21.2 --config rollup-config.mjs'

[[task]]
name = 'test'
deps = ['build']
run = 'code --extensionDevelopmentPath=$JSPM_VSCODE_PATH --extensionDevelopmentKind=web'

[[task]]
name = 'publish'
run = 'vsce publish'

[env]
JSPM_VSCODE_PATH='/Users/jk/Documents/jspm/jspm-vscode'
